#!/usr/bin/env python3
"""
Mock Codex CLI that simulates a code-focused agent response.
"""

from __future__ import annotations

import json
import sys
from datetime import datetime
from typing import Any, Dict


def read_payload() -> Dict[str, Any]:
    raw = sys.stdin.read()
    if not raw.strip():
        return {}
    try:
        return json.loads(raw)
    except json.JSONDecodeError as exc:  # pragma: no cover - defensive path
        print(f"[mock_codex] Invalid JSON payload: {exc}", file=sys.stderr)
        raise SystemExit(1) from exc


def code_snippet(task: str) -> str:
    """Return a fenced code block showing a pseudo-implementation."""
    snippet = (
        "# pseudo-implementation generated by mock_codex\n"
        f"def handle_task():\n"
        f"    \"\"\"Auto-generated plan for: {task}\"\"\"\n"
        f"    return \"success\"\n"
    )
    return f"```python\n{snippet}```"


def main() -> int:
    payload = read_payload()
    state = payload.get("state") or {}
    task = payload.get("task") or "Unspecified task"
    agent_name = payload.get("agent_name", "coder")
    steps_completed = len(state.get("execution_history", []))

    summary_lines = [
        f"{agent_name} mock (Codex flavor) focused on implementation details "
        f"for: **{task}**.",
        f"Detected {steps_completed} prior execution steps in TEAM MEMORY.",
        "Prepared code-oriented artifacts to guide subsequent testing.",
    ]

    print("## SUMMARY")
    for line in summary_lines:
        print(f"- {line}")

    print("\n## ARTIFACTS")
    print(code_snippet(task))
    print()
    print("```json")
    print(
        json.dumps(
            {
                "generated_at": datetime.utcnow().isoformat() + "Z",
                "agent_name": agent_name,
            },
            indent=2,
        )
    )
    print("```")

    print("\n## NEXT_ACTION")
    print(
        "Request validation from the devops agent to ensure implementation "
        "matches infrastructure expectations."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
